name: business_suite_mobile_pos
description: Business Suite Mobile Pos

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # drawer
  flutter_slider_drawer: ^2.1.1
  # app icon
  flutter_launcher_icons: ^0.9.2

  # For Architecture
  provider: ^6.0.1

  #Dependency Injection
  get_it: ^7.2.0
  get: ^4.3.8

  #For Networking
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.0
  #For large log
  logger: ^1.1.0
  pretty_dio_logger: ^1.1.1
  #Lazy Json Serialization
  json_serializable: ^6.1.1
  json_annotation: ^4.4.0

  # Reactive Programming
  rxdart: ^0.27.5
  #event bus
  event_bus: ^2.0.0

  #For UI
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  flutter_svg: ^0.23.0+1
  bouncing_widget: ^2.0.0
  roundcheckbox: ^2.0.4
  flutter_staggered_grid_view: ^0.6.1
  expandable: ^5.0.1
  custom_radio_grouped_button: ^2.1.2
  #multi adapting screen and font size
  flutter_screenutil: ^5.0.0+2
  intl: ^0.17.0
  #format date time for parsing
  jiffy: ^4.1.0
  flutter_spinkit: ^5.1.0
  page_transition: ^2.0.4
  webview_flutter: ^2.3.1
  transparent_image: ^2.0.0

  # For Google and Firebase
  #control notification in android & ios
  flutter_local_notifications: ^9.0.3

  #For Local Storage
  shared_preferences: ^2.0.15

  # Package Info
  device_info_plus: ^3.1.1
  package_info: ^2.0.2

  #For Permission
  permission_handler: ^8.1.2

  #File path
  path_provider: ^2.0.1

  #For access local image
  image_picker: ^0.8.4+10

  #For File Picker:
  file_picker: ^4.4.0

  #launch browser
  url_launcher: ^6.0.18

  #format string
  sprintf: ^6.0.0

  # save widget as image
  screenshot: ^1.2.3

  #Share to SNS
  share: ^2.0.4

  #Flutter Flavors Dev & Prod
  flutter_flavorizr: ^2.1.3

  #multiple language
  easy_localization: ^3.0.1

  smooth_page_indicator: ^0.3.0-nullsafety.0
  percent_indicator: ^3.3.0-nullsafety.1

  flutter_scale_tap:
    git: https://github.com/magicpro97/flutter_scale_tap
  font_awesome_flutter: ^10.1.0

  #rpc
  grpc: ^3.0.2
  protobuf: ^2.1.0

  #http
  http: ^0.13.4

  #generator and check otp Google Authenticator
  otp: ^3.1.1

  #parse html
  html: ^0.15.0

  #gen SHA1, SHA256...
  crypto: ^3.0.2


  #item action bottom sheet
  adaptive_action_sheet: ^2.0.2

  responsive_framework: ^0.2.0

  #validator server & port
  string_validator: ^0.3.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  #auto gen
  build_runner:


#ICON LAUNCHER
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/ic_launcher.png"


#Flavor Dev & Prod
flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "Business Suite Pos(dev)"
      android:
        applicationId: "com.businesssuite.business_suite_mobile_pos"
      ios:
        bundleId: "com.businesssuite.business_suite_mobile_pos"

    production:
      app:
        name: "Business Suite Pos"
      android:
        applicationId: "com.businesssuite.business_suite_mobile_pos"
      ios:
        bundleId: "com.businesssuite.business_suite_mobile_pos"


flutter:
  uses-material-design: true

  # res icon, image, sound...
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/translations/
    - assets/animations/
    - assets/animations/onboarding/
    - assets/animations/onboarding/images/